language: cpp
compiler: 
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal-dev libwxgtk3.0-dev swig python-dev libproj-dev libvigraimpex-dev
  - cd saga-gis
  - autoreconf -fi
script: ./configure && make
#addons:
#  apt:
#    sources:
#    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
#    packages:
#    - libgdal-dev
#    - libwxgtk3.0-dev
#    - swig
#    - python-dev
#    - libproj-dev
